[tool.black]
line-length = 88
target_version = ['py37', 'py38', 'py39']
preview = true

[tool.isort]
profile='black'
line_length = 88
known_third_party = ["docs","tests","examples"]
force_sort_within_sections = "False"
order_by_type = "False"