name: snapshot

on:
  workflow_run:
    workflows: ["test"]
    branches: ["main"]
    types: [completed]

jobs:

  snapshot:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/biquality-learn
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - uses: actions/setup-python@v5
    - run: uv build 
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/simple/